
---
- name: Install Docker
  hosts: all 
  vars:
    DOCKER_COMPOSE_VERSION: "2.6.1"
    USER: "shakir"
    DOCKER_PACKAGES:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    
  become: yes
  tasks:
    - name: Install essential packages
      apt: 
        name: "{{ DOCKER_PACKAGES }}" 
        state: present 
        update_cache: yes
        force_apt_get: yes
    
    - name: Add Docker GPG key
      apt_key: 
        url: "https://download.docker.com/linux/ubuntu/gpg" 
        state: present
    
    - name: Save Ubuntu release version into a variable
      shell: "lsb_release -cs"
      register: os_version
    
    - name: Add Docker apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ os_version.stdout }} stable"
        state: present
    
    - name: Install Docker
      apt: 
        state: present 
        update_cache: yes 
        force_apt_get: yes
        name: 
          - docker-ce
          - docker-ce-cli 
          - containerd.io

    
    # 'state: present' -> if group exist = pass; otherwise create it. 
    - name: Create Docker Group
      group:
        name: "docker"
        state: present
    
    - name: Add user {{ USER }} to docker group
      user:
        name: "{{ USER }}"
        groups: "docker"
        append: yes
    
    - name: Ensure docker service is running
      systemd: 
        name: docker 
        state: started 
        enabled: yes   

    - name: Install Docker Compose
      get_url:
        url:  "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-Linux-x86_64"
        dest: "/usr/local/bin/docker-compose"
        mode: 0755

    - name: Reboot
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
